version: "3"

services:
  flask:
    build: .
    ports:
      - "3031:3031"
      - "9090:9090"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./profiles:/src/profiles
