services:
  flask:
    build: .
    container_name: flask
    ports:
      - "3031:3031"
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/src/www
